name: company_analytics
description: "Internal Flutter analytics facade for Facebook App Events and Singular."
version: 0.0.6
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  app_tracking_transparency: ^2.0.7
  crypto: ^3.0.7
  facebook_app_events:
    path: third_party/facebook_app_events
  singular_flutter_sdk:
    path: third_party/singular_flutter_sdk
  shared_preferences: ^2.5.5
  yaml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  company_analytics: company_analytics

flutter:
