import 'dart:io';

import 'package:yaml/yaml.dart';

void main(List<String> args) {
  if (args.isEmpty) {
    _usageAndExit('Missing required args.');
  }

  String? appRoot;
  String? yamlPath;

  for (var i = 0; i < args.length; i++) {
    final arg = args[i];
    if (arg == '--app-root' && i + 1 < args.length) {
      appRoot = args[++i];
      continue;
    }
    if (arg == '--config' && i + 1 < args.length) {
      yamlPath = args[++i];
      continue;
    }
  }

  if (appRoot == null || yamlPath == null) {
    _usageAndExit('Both --app-root and --config are required.');
  }

  final appRootDir = Directory(appRoot);
  if (!appRootDir.existsSync()) {
    _fail('App root does not exist: $appRoot');
  }

  final configFile = File(yamlPath);
  if (!configFile.existsSync()) {
    _fail('YAML config not found: $yamlPath');
  }

  final yaml = loadYaml(configFile.readAsStringSync());
  if (yaml is! YamlMap) {
    _fail('Invalid yaml structure. Root must be a map.');
  }

  final facebook = yaml['facebook'];
  if (facebook is! YamlMap) {
    _fail('Missing facebook section in yaml.');
  }

  final singular = yaml['singular'];
  if (singular is! YamlMap) {
    _fail('Missing singular section in yaml.');
  }

  final appId = _readRequiredString(facebook, 'facebook.app_id');
  final clientToken = _readRequiredString(facebook, 'facebook.client_token');
  final displayName = _readOptionalString(facebook, 'display_name') ?? 'App';

  final singularApiKey = _readRequiredString(singular, 'singular.api_key');
  final singularSecret = _readRequiredString(singular, 'singular.secret');

  _writeAndroidFiles(appRootDir, appId, clientToken);
  _writeIosFiles(appRootDir, appId, clientToken, displayName);
  _writeDartEnvFile(
    appRootDir,
    appId: appId,
    clientToken: clientToken,
    displayName: displayName,
    singularApiKey: singularApiKey,
    singularSecret: singularSecret,
  );

  stdout.writeln('Done. Analytics native/dart config generated successfully.');
  stdout.writeln(
    'Next: run check script: bash tool/check_facebook_setup.sh ${appRootDir.path}',
  );
}

void _writeAndroidFiles(Directory appRoot, String appId, String clientToken) {
  final androidValuesDir = Directory(
    '${appRoot.path}/android/app/src/main/res/values',
  );
  androidValuesDir.createSync(recursive: true);

  final facebookXml = File('${androidValuesDir.path}/facebook_config.xml');
  facebookXml.writeAsStringSync('''<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="facebook_app_id">$appId</string>
  <string name="facebook_client_token">$clientToken</string>
  <string name="fb_login_protocol_scheme">fb$appId</string>
</resources>
''');

  stdout.writeln('Wrote ${facebookXml.path}');
}

void _writeIosFiles(
  Directory appRoot,
  String appId,
  String clientToken,
  String displayName,
) {
  final iosFlutterDir = Directory('${appRoot.path}/ios/Flutter');
  iosFlutterDir.createSync(recursive: true);

  final fbConfig = File('${iosFlutterDir.path}/FacebookConfig.xcconfig');
  fbConfig.writeAsStringSync(
    '''// Generated by company_analytics/tool/sync_analytics_config.dart
FACEBOOK_APP_ID=$appId
FACEBOOK_CLIENT_TOKEN=$clientToken
FACEBOOK_DISPLAY_NAME=$displayName
''',
  );

  _ensureInclude('${iosFlutterDir.path}/Debug.xcconfig');
  _ensureInclude('${iosFlutterDir.path}/Release.xcconfig');
  _ensureInclude('${iosFlutterDir.path}/Profile.xcconfig');

  stdout.writeln('Wrote ${fbConfig.path}');
  stdout.writeln(
    'Ensured FacebookConfig.xcconfig include in iOS xcconfig files.',
  );
  stdout.writeln(
    'Reminder: Info.plist should use \$(FACEBOOK_APP_ID), \$(FACEBOOK_CLIENT_TOKEN), and fb\$(FACEBOOK_APP_ID).',
  );
}

void _writeDartEnvFile(
  Directory appRoot, {
  required String appId,
  required String clientToken,
  required String displayName,
  required String singularApiKey,
  required String singularSecret,
}) {
  final dartOutDir = Directory('${appRoot.path}/lib/generated');
  dartOutDir.createSync(recursive: true);

  final envFile = File('${dartOutDir.path}/analytics_env.g.dart');
  envFile.writeAsStringSync('''// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by company_analytics/tool/sync_analytics_config.dart

class AnalyticsEnv {
  static const String facebookAppId = '$appId';
  static const String facebookClientToken = '$clientToken';
  static const String facebookDisplayName = '$displayName';

  static const String singularApiKey = '$singularApiKey';
  static const String singularSecret = '$singularSecret';
}
''');

  stdout.writeln('Wrote ${envFile.path}');
}

void _ensureInclude(String path) {
  final file = File(path);
  if (!file.existsSync()) {
    return;
  }

  final includeLine = '#include? "FacebookConfig.xcconfig"';
  final content = file.readAsStringSync();

  if (!content.contains(includeLine)) {
    final newContent = '$includeLine\n$content';
    file.writeAsStringSync(newContent);
  }
}

String _readRequiredString(YamlMap map, String keyForError) {
  final rawKey = keyForError.split('.').last;
  final value = map[rawKey];
  if (value is String && value.trim().isNotEmpty) {
    return value.trim();
  }
  _fail('Missing required key: $keyForError');
}

String? _readOptionalString(YamlMap map, String key) {
  final value = map[key];
  if (value is String && value.trim().isNotEmpty) {
    return value.trim();
  }
  return null;
}

Never _fail(String message) {
  stderr.writeln('ERROR: $message');
  exit(1);
}

Never _usageAndExit(String message) {
  stderr.writeln(message);
  stderr.writeln('Usage:');
  stderr.writeln(
    '  dart run tool/sync_analytics_config.dart --app-root <flutter_app_root> --config <yaml_path>',
  );
  exit(2);
}
